In [2]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

In [6]:
df = pd.read_csv("Algerin Fire.csv")

In [7]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 243 entries, 0 to 242
Data columns (total 12 columns):
 #   Column       Non-Null Count  Dtype  
---  ------       --------------  -----  
 0   Temperature  243 non-null    int64  
 1   RH           243 non-null    int64  
 2   Ws           243 non-null    int64  
 3   Rain         243 non-null    int64  
 4   FFMC         243 non-null    float64
 5   DMC          243 non-null    float64
 6   DC           243 non-null    float64
 7   ISI          243 non-null    float64
 8   BUI          243 non-null    float64
 9   FWI          243 non-null    float64
 10  Classes      243 non-null    int64  
 11  Region       243 non-null    int64  
dtypes: float64(6), int64(6)
memory usage: 22.9 KB


In [10]:
x = df.drop('FWI',axis=1)

In [12]:
y= df['FWI']

In [13]:
y

0      0.5
1      0.4
2      0.1
3      0.0
4      0.5
      ... 
238    6.5
239    0.0
240    0.2
241    0.7
242    0.5
Name: FWI, Length: 243, dtype: float64

In [14]:
#Train test split
from sklearn.model_selection import train_test_split

In [18]:
x_train,x_test,y_train,y_test = train_test_split(x,y,test_size=0.25,random_state=10)

In [25]:
x_test.shape,y_test.shape,x_train.shape,y_train.shape

((61, 11), (61,), (182, 11), (182,))

In [32]:
def corellation(dataset,threshold):
    col_corr = set()
    corr_martix = dataset.corr()
    for i in range (len(corr_martix.columns)):
        for j in range (i):
            if abs(corr_martix.iloc[i,j]) > threshold:
                colname = corr_martix.columns[i]
                col_corr.add(colname)
    return col_corr

In [34]:
corr_feture = corellation(x_train,0.85)

In [35]:
corr_feture

{'BUI', 'DC'}

In [36]:
x_train.drop(corr_feture,axis=1,inplace=True)
x_test.drop(corr_feture,axis=1,inplace=True)

In [40]:
x_train.shape

(182, 9)

In [42]:
from sklearn.preprocessing import StandardScaler
scaler = StandardScaler()

In [46]:
x_train_scaled = scaler.fit_transform(x_train)
x_test_scaled = scaler.transform(x_test)

In [47]:
x_test_scaled

array([[-8.22462036e-01,  4.67000417e-01, -5.99049163e-01,
        -3.34125866e-01,  3.82324752e-01, -4.03032864e-01,
        -3.57077199e-01,  9.15633026e-01, -1.00000000e+00],
       [-8.22462036e-01, -9.31804908e-01,  1.21202970e+00,
        -3.34125866e-01,  7.70459017e-01, -2.40355537e-01,
         1.04537158e+00,  9.15633026e-01,  1.00000000e+00],
       [ 1.10721869e+00, -4.65536466e-01,  1.25382383e-01,
        -3.34125866e-01,  7.90534928e-01,  7.12468805e-01,
         8.31438717e-01,  9.15633026e-01,  1.00000000e+00],
       [-1.64946806e+00,  1.19970797e+00,  1.93646125e+00,
         2.43000630e+00, -1.90632902e+00, -8.98811384e-01,
        -1.02264611e+00, -1.09214060e+00, -1.00000000e+00],
       [-8.22462036e-01,  1.13309819e+00, -5.99049163e-01,
         7.71527000e-01, -1.89963705e+00, -9.60783698e-01,
        -1.04641643e+00, -1.09214060e+00,  1.00000000e+00],
       [ 5.55881339e-01, -3.32316911e-01,  1.25382383e-01,
        -3.34125866e-01,  7.36999167e-01,  1.022330

# Leanear Regresion model

In [48]:
from sklearn.linear_model import LinearRegression
regression = LinearRegression()

In [49]:
regression.fit(x_train_scaled,y_train)

LinearRegression()

In [50]:
y_pred = regression.predict(x_test_scaled)

In [51]:
y_pred

array([ 4.34229082, 10.66397801, 12.97823971,  0.43025134, -1.0195259 ,
       13.19931009,  3.1970029 , 17.03025454,  6.68695324,  1.63525047,
        1.34152974,  7.23998743, 10.56067785, 11.26440346,  6.5756185 ,
       14.37956599,  0.1356654 , 20.96899991,  6.07002637,  2.51485787,
        4.79222784,  1.8220276 , 14.64634446,  1.17872127,  0.33077304,
        9.50765182,  1.70646448,  1.80079003,  0.89236348,  1.79868916,
        7.85986294,  5.14003685,  3.8559664 ,  8.34446252, 16.3630632 ,
        0.14702646,  1.33881989,  0.57330873, 13.92307394,  1.07785295,
       14.35877177, 10.408739  , 11.42360717,  7.72153976,  9.83926786,
       25.01512242,  0.66036252, 13.89362214, -0.23377977,  2.74965827,
        6.52183969, 22.98805731,  3.20592902,  8.26113237, -0.46888194,
       25.46697514, 11.90166172,  4.18663435,  0.22805266,  4.84568304,
       11.73423816])

In [53]:
from sklearn.metrics import mean_squared_error
from sklearn.metrics import mean_absolute_error

In [55]:
mae = mean_absolute_error(y_test,y_pred)
mae

0.6122362236444738

In [56]:
from sklearn.metrics import r2_score

In [57]:
score = r2_score(y_test,y_pred)
score

0.9842968634036315

# Lasso Regression

In [59]:
from sklearn.linear_model import Lasso

In [60]:
lasso =Lasso()

In [61]:
lasso.fit(x_train_scaled,y_train)

Lasso()

In [62]:
y_pred = lasso.predict(x_test_scaled)

In [63]:
y_pred

array([ 4.40903936, 10.34980893, 12.42143749,  0.31472758,  0.03367003,
       12.53462931,  3.93443053, 15.72125133,  7.24172704,  2.57424408,
        3.26269701,  6.97799533, 10.14729151, 10.30019192,  6.61388195,
       12.82525945,  0.19883939, 19.1468618 ,  5.87884422,  1.84426324,
        4.58256843,  3.03301055, 13.04058702,  3.01359478,  1.37713707,
        9.59144618,  2.9607402 ,  3.45833821,  2.15161279,  2.59932319,
        7.48037964,  5.81075372,  4.40903936,  7.84894347, 14.38850452,
        0.87057291,  2.97118983,  2.36606332, 12.50179694,  2.21612988,
       13.5755331 , 10.12848218, 10.45612454,  7.60489813,  9.09802802,
       22.47532817,  2.38965895, 12.50537035,  1.76781304,  3.12381964,
        6.33821713, 20.87709556,  3.46730436,  7.82595429, -0.36536564,
       22.60193658, 11.55257928,  5.58821408,  2.0440843 ,  4.72414217,
       10.70610381])

In [64]:
y_test

46      3.6
225    10.3
180    13.2
116     0.1
124     0.1
       ... 
148    12.0
232     3.8
136     0.6
49      4.0
58     11.9
Name: FWI, Length: 61, dtype: float64

In [66]:
mae = mean_absolute_error(y_test,y_pred)
mae

1.1914563519929364

In [67]:
score = r2_score(y_test,y_pred)
score

0.9507719279946633

# Ridge Regression

In [68]:
from sklearn.linear_model import Ridge
ridge = Ridge()

In [70]:
ridge.fit(x_train_scaled,y_train)

Ridge()

In [71]:
y_pred = ridge.predict(x_test_scaled)

In [72]:
y_pred

array([ 4.38508655, 10.67518531, 12.97564012,  0.42174979, -1.05729411,
       13.20189033,  3.23907299, 17.00432865,  6.71821973,  1.68979174,
        1.36613481,  7.25987604, 10.61763456, 11.25474652,  6.67930234,
       14.36504422,  0.09168475, 20.85202861,  6.1097623 ,  2.52370338,
        4.88857051,  1.8603242 , 14.64110251,  1.19193252,  0.34876223,
        9.52427251,  1.72527825,  1.84594786,  0.92393086,  1.77713973,
        7.87917901,  5.19656043,  3.97557895,  8.36065475, 16.3742975 ,
        0.12752275,  1.40898026,  0.62456811, 13.90716846,  1.14474475,
       14.34736348, 10.42562496, 11.42227095,  7.78429917,  9.8604901 ,
       24.87405879,  0.71621746, 13.87302199, -0.18764844,  2.79077633,
        6.54623917, 22.8645854 ,  3.26329336,  8.26998674, -0.52966917,
       25.38380931, 11.90240705,  4.21257207,  0.19617994,  4.91266402,
       11.72364341])

In [73]:
mae = mean_absolute_error(y_test,y_pred)
mae

0.6358781922976218

In [75]:
score = r2_score(y_test,y_pred)
score

0.983480604567744

In [76]:
from sklearn.linear_model import ElasticNet
elnet = ElasticNet()

In [77]:
elnet.fit(x_train_scaled,y_train)

ElasticNet()

In [79]:
y_pred = elnet.predict(x_test_scaled)
y_pred

array([ 5.8239622 , 10.27052846, 12.10223316,  0.12768492,  0.05162226,
       12.20896252,  4.14350207, 14.70284846,  7.92199662,  3.53344442,
        3.89927373,  7.84512913, 11.03560047, 10.09867962,  8.3213624 ,
       12.27438195,  0.05721629, 16.76012122,  7.10600407,  1.49065107,
        6.47641578,  3.55782292, 12.53185465,  3.63990478,  1.70209816,
        9.85583861,  3.57088382,  3.61836244,  2.80832051,  3.15710371,
        8.43440072,  7.24668619,  6.85787019,  8.45162963, 13.37091897,
        0.88638208,  3.75806542,  3.00047721, 11.94432049,  3.4317825 ,
       13.0750664 , 10.51052598, 10.67680351,  9.35931204,  9.53018848,
       19.45052761,  3.15567721, 12.35305775,  2.07456725,  4.65803699,
        7.29424858, 18.82415343,  5.24323536,  8.78363484, -0.5544723 ,
       20.08200033, 11.4804269 ,  5.65615567,  1.55272623,  6.39670824,
       10.5025961 ])

In [80]:
mae = mean_absolute_error(y_test,y_pred)
mae

1.8874637022540437

In [81]:
score = r2_score(y_test,y_pred)
score

0.880344502474426

In [83]:
import pickle
pickle.dump(scaler,open('scaler.pkl','wb'))
pickle.dump(ridge,open('ridge.pkl','wb'))